### ISSUE TITLE
Protofile not up to date, other issues

### ISSUE THREAD

**Issue by imperator-maximus** [Stability-AI/stability-sdk#50]
Hello,

you said that people should using generation.proto but this does not work to be honest. It is not based on your current API.
So many very important parameters are missing here:
- scheduleParameters (used in Python client)
- mask artifact type

Also in PromptParameters there is a "weight" float which nobody know how to use it. It does not make sense.
There is also no masking example and juest with wild guesses there will garbage results. 
Using "improbable-eng/grpc-web" in your example JS is also a not so good idea because it just does not work in every browser environment (official grpc-web has no issues). Your example Colab does not use current API as well.

I am on a tight deadline and so your client API is useless for me at the moment. Can you provide a contact person in your company who can help the find the correct parameters - please contact me on Twitter: https://twitter.com/NicolayMausz 
Thank you very much!

**Comment by dmarx** [comment]
The canonical protbuf definitions can be found here: https://github.com/Stability-AI/api-interfaces/blob/main/src/proto/generation.proto . That repository wasn't publicly visible when we published the SDK, and we're currently in the process of updating this repo to submodule the canonical api repo directly rather than vendoring the requisite files like we currently are. I apologize for any inconvenience or confusion that has caused. 

If you look in the nbs directory, you'll see a demo notebook that includes among other things a masking demo.

Regarding the 'weight' parameter: that is a parameter that is public in the API but is not yet tied to publicly available functionality. I can understand how that would be confusing, and we hope to have improved developer documentation shortly. Our team is still quite small, please bear with us (can you believe it hasn't even been a month since the public launch?).
